apiVersion: v1
kind: ConfigMap
metadata:
  name: personalweb-mainconfig
data:
  mainconfig.json: |-
    {
        "headerLogMode": "{{ .Values.configSettings.headerLogMode }}",
        "monitorAddedHeader": "{{ .Values.configSettings.monitorAddedHeader }}",
        "monitorUrl": "{{ .Values.configSettings.monitorUrl }}",
        "siteKey": "{{ .Values.configSettings.siteKey }}",
        "visitorIdCookieName": "{{ .Values.configSettings.visitorIdCookieName }}"
    }