apiVersion: v1
kind: Secret
metadata:
  name: {{ include "personalweb.fullname" . }}
  namespace: default
type: Opaque
stringData:
  secrets.json: |-
    {
        "SiteCountsConnectionString": "Host={{ .Values.database.host }};Database={{ .Values.database.dbname }};Username={{ .Values.database.username }};Password={{ .Values.database.password }}"
    }  