apiVersion: v1
kind: Service
metadata:
  name: {{ include "personalweb.fullname" . }}
  labels:
    {{- include "personalweb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: main
      nodePort: {{ .Values.service.port }}
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    {{- include "personalweb.selectorLabels" . | nindent 4 }}
